#include <tinystl/util.h>
#include <catch2/catch_all.hpp>
#include <vector>

/*
 * WARN: this test is generated by Github Copilot.
 */

using namespace tinystl;

TEST_CASE("Utils Tests", "[util]") {
    SECTION("Move function") {
        // Create a vector
        std::vector<int> v1;
        v1.push_back(1);
        v1.push_back(2);
        v1.push_back(3);

        // Move the vector to a new vector
        std::vector<int> v2 = tinystl::move(v1);

        // Check if the original vector is empty
        REQUIRE(v1.empty());

        // Check if the new vector has the correct elements
        REQUIRE(v2.size() == 3);
        REQUIRE(v2[0] == 1);
        REQUIRE(v2[1] == 2);
        REQUIRE(v2[2] == 3);
    }
}